{
 "title": "PAM - Openshift",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kie_server_start_time{},namespace)"
    }
   },
   {
    "name": "kieapp",
    "label": "Kie-App",
    "query": {
     "query": "label_values(kie_server_start_time,server_id)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(up{ namespace=~\"$namespace\",container=~\"$kieapp\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kie-app Summary - $namespace Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Kie server state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{ namespace=~\"$namespace\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Kie Server Start TIme",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_start_time{ namespace=~\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container)(kie_server_container_running_total{namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container)(kie_server_deployments_active_total{ namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container)(kie_server_process_instance_running_total{namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Running Cases",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_case_running_total{ namespace=~\"$namespace\"}",
     "legendFormat": "{{case_definition_id}}"
    }
   ]
  },
  {
   "title": "Started Processes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container)(kie_server_process_instance_started_total{ namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Started Cases",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container)(kie_server_case_started_total{ namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "SLA Violations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_process_instance_sla_violated_total{ namespace=~\"$namespace\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Execution Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_execution_error_total{ namespace=~\"$namespace\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_task_failed_total{ namespace=~\"$namespace\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Exited Tasks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_task_exited_total{ namespace=~\"$namespace\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  { "title": "Kie-app status - $kieapp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "kieapp" },
  {
   "title": "Kie Server State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{ namespace=~\"$namespace\",service=~\"$kieapp\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Kie Server Start TIme",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_start_time{namespace=~\"$namespace\",service=~\"$kieapp\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_container_running_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_deployments_active_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_job_running_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Running Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_case_running_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_process_instance_running_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_task_added_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "SLA Violations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_process_instance_sla_violated_total{ namespace=~\"$namespace\",service=~\"$kieapp\"}"
    }
   ]
  },
  {
   "title": "Execution Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kie_server_execution_error_total{ namespace=~\"$namespace\",service=~\"$kieapp\"}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_task_failed_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Exited Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_task_exited_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Started Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_process_instance_started_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Started Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_case_started_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Registered Data Set Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_data_set_registered_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Running Data Set Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kie_server_data_set_lookups_total{ namespace=~\"$namespace\",service=~\"$kieapp\"})"
    }
   ]
  },
  {
   "title": "Data Set Queries Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(kie_server_data_set_execution_time_seconds_sum{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Data Set Query Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kie_server_data_set_execution_time_seconds_count{ namespace=~\"$namespace\",service=~\"$kieapp\"}"
    }
   ]
  },
  {
   "title": "Started Process Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kie_server_process_instance_started_total{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Process Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_process_instance_duration_seconds_sum{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Work Item Average Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_work_item_duration_seconds_sum{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Items Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "kie_server_work_item_duration_seconds_count{ namespace=~\"$namespace\",service=~\"$kieapp\"}"
    }
   ]
  },
  {
   "title": "Case Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_case_duration_seconds_sum{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{case_definition_id}}"
    }
   ]
  },
  {
   "title": "Task Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_task_duration_seconds_sum{ namespace=~\"$namespace\",service=~\"$kieapp\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "JBoss EAP Metrics - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 }, "repeat": "pod" },
  {
   "title": "Jboss Datasource Active connections",
   "type": "timeseries",
   "description": "JBoss Datasources Active connection cout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "jboss_datasources_pool_active_count{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{data_source}}{{xa_data_source}}"
    }
   ]
  },
  {
   "title": "Jboss Datasources Pool Average Usage Time",
   "type": "timeseries",
   "description": "The average time spent using a physical connection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "jboss_datasources_pool_average_usage_time_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{data_source}}{{xa_data_source}}"
    }
   ]
  },
  {
   "title": "Base Memory - Used Heap Details(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\", pool=~\"(PS.+)\"}/1024)/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\"$pod\", container=\"\"}/1024)/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (Mi)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=~\"$namespace\",pod=~\"$pod\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Request Processing time (Secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "(jboss_undertow_processing_time_total{namespace=~\"$namespace\",pod=~\"$pod\"}/jboss_undertow_request_count_total{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}} ({{http_listener}} listener)"
    }
   ]
  }
 ]
}